version: '3'
services:
  web:
    build: .
    command: python django_app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/scraper  # scraperディレクトリを指定
    depends_on:
      - db
    environment:
      - DISPLAY=:99
      - PYTHONPATH=/app  # PYTHONPATHを設定

  db:
    image: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
